# Facility Booking API Application Configuration

# Server
server.port=8080

# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:bookingdb;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=cdl
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console (http://localhost:8080/h2-console) : small scale work bench for h2 db
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logging
logging.level.com.example.facilitybooking=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.web.servlet.resource=WARN
